Task/04 astar/egorov gordei
mipt-backend-academy-winter-2023/team-2 pull request #12
Opened 2023-09-17 20:51 UTC by GIS-sys

2023-09-18 15:10 UTC, mikhailchuryakov commented
Все хорошо, спасибо за ридми и правки старта приложения. Есть незначительные замечания. И нужно форматировать код (использовать scalafmt) перед отправкой

2023-09-18 15:10 UTC, mikhailchuryakov requested changes
Все хорошо, спасибо за ридми и правки старта приложения. Есть незначительные замечания. И нужно форматировать код (использовать scalafmt) перед отправкой

2023-09-18 15:10 UTC, mikhailchuryakov commented on routing/src/main/resources/routedb/migration/V2__create_edge_table.sql
> +CREATE TRIGGER update_distance BEFORE INSERT ON "edge" FOR EACH ROW EXECUTE FUNCTION func_update_distance();
В промышленной разработке стоит избегать триггеров и функций в бд - плохой тон переносить хоть какую-то логику в базу данных, ее используются только для хранения/чтения. Для этой задачи пойдет, исправлять не нужно

2023-09-18 15:10 UTC, mikhailchuryakov commented on routing/src/main/scala/routing/api/HttpRoutes.scala
> +          fromId <- ZIO.succeed(fromIdStr.toInt)
Нет смысла оборачивать в эффект. в for-comprehension есть такая конструкция

`fromId = fromIdStr.toInt`

2023-09-18 15:10 UTC, mikhailchuryakov commented on routing/src/main/scala/routing/config/Config.scala
> +object ConfigImpl {
Объекты компаньоны лучше располагать с классом, повышает читабельность

2023-09-18 15:10 UTC, mikhailchuryakov commented on routing/src/main/scala/routing/flyway/FlywayAdapter.scala
> +object FlywayAdapter {
Эта сущность полностью дублирует auth.flyway.FlywayAdapter. Копипаст нужно избегать и если сущности похожи, то нужно выносить общую часть. Здесь лучше вынести Flyway в какие-нибудь утиля

2023-09-18 15:10 UTC, mikhailchuryakov commented on routing/src/main/scala/routing/utils/Graph.scala
> +      }
Кажется (не проверял логику работу) эта конструкция то же самое, что и 
`NodeRepository.findAllNodes.runCollect.map(n => nodes ++= n.toArray[Node])`
Ребра аналогично

2023-09-18 17:41 UTC, GIS-sys commented on routing/src/main/scala/routing/flyway/FlywayAdapter.scala
> +object FlywayAdapter {
routing.flyway.FlywayAdapter отличается от своего собрата в auth опцией .locations, так как у нас две разные базы данных с разными миграциями

2023-09-27 04:59 UTC, mikhailchuryakov commented on routing/src/main/scala/routing/flyway/FlywayAdapter.scala
> +object FlywayAdapter {
Но сущность, которая катит миграции одна. Она должна быть обстрагирована от базы и от наполнения и получать на вход что и куда отправить

2023-09-27 12:54 UTC, mikhailchuryakov approved these changes
👍

2023-09-27 12:54 UTC, merged