Task/07 ci/egorov gordei
mipt-backend-academy-winter-2023/team-2 pull request #20
Opened 2023-10-16 01:36 UTC by GIS-sys

2023-10-16 21:22 UTC, GIS-sys commented
сделал задание из своей ветки, так как уже давно ничего не сливали. Если сольют другую ветку в домашке 6 - скопирую измнения туда

2023-10-17 15:19 UTC, mikhailchuryakov requested changes
Поменяй таргет на мастер плз, смержил твою ветку

2023-10-17 19:00 UTC, GIS-sys commented
> Поменяй таргет на мастер плз, смержил твою ветку

Поменял на мастер

2023-10-22 15:01 UTC, mikhailchuryakov requested changes
Нужно спуллить мастер

2023-10-22 15:49 UTC, mikhailchuryakov requested changes

2023-10-22 15:49 UTC, mikhailchuryakov commented on auth/src/test/scala/auth/AuthTest.scala
> +object AuthSpec extends ZIOSpecDefault {
Название файла отличается от класса

2023-10-22 15:49 UTC, mikhailchuryakov commented on .gitignore
> +src/images/**
Думаю стоит убрать из гитигнора, пускай у всех будут тесты. И для такого есть папка resources

2023-10-22 15:49 UTC, mikhailchuryakov commented on routing/src/test/scala/routing/RoutingTest.scala
> +          assertTrue(1 == 2)
А это что за ассерт?

2023-10-22 15:49 UTC, mikhailchuryakov commented on routing/src/test/scala/routing/RoutingTest.scala
> +          assertTrue(1 == 2)
https://scala.monster/zio-test/#:~:text=The%20biggest%20trap%20I%20have%20fallen%20with%20ZIO%20Test.

2023-10-22 15:49 UTC, mikhailchuryakov commented on images/src/test/scala/images/ImagesTest.scala
> +          assertTrue(response.status == Status.Ok)
https://scala.monster/zio-test/#:~:text=The%20biggest%20trap%20I%20have%20fallen%20with%20ZIO%20Test.

2023-10-22 15:49 UTC, mikhailchuryakov commented on project/Libs.scala
> +    "org.scalatest" %% "scalatest" % V.test % Test,
А зачем вам всем scalatest?

2023-10-23 15:26 UTC, GIS-sys commented on project/Libs.scala
> +    "org.scalatest" %% "scalatest" % V.test % Test,
Я начинал писать тесты для зио как обычные тесты, пока не понял, что это так не работает, и забыл убрать. Убрал

2023-10-23 15:34 UTC, GIS-sys commented on .gitignore
> +src/images/**
А это не тесты, это папка, в которой в текущем мастере хранятся все картинки из сервиса images. То есть если я запущу sbt run и сделаю curl запрос на добавление картинки, именно тут она сохранится. Такую папку вряд ли надо хранить в гитхабе

2023-10-23 15:50 UTC, GIS-sys commented on routing/src/test/scala/routing/RoutingTest.scala
> +          assertTrue(1 == 2)
Точно, я пытался понять, почему он тесты проходятся, несмотря на этот assert, а потом забыл про него и сделал пулл реквест. Спасибо за ссылку, разобрался, поправил!

2023-10-31 06:54 UTC, mikhailchuryakov commented on .gitignore
> +src/images/**
А как другим запускать такие тесты? У них же нет этих фотографий локально
Для тестов я бы вынес отдельно

2023-10-31 06:55 UTC, mikhailchuryakov approved these changes
Все хорошо. Смержим мр Антона, у него больше понравились тесты на изображения

2023-10-31 06:57 UTC, closed without merging