task7/antonis-white
mipt-backend-academy-winter-2023/team-2 pull request #23
Opened 2023-10-18 15:36 UTC by antonis-white

2023-10-22 15:00 UTC, mikhailchuryakov requested changes
В cicd не проходит линтер, нужно его поправить и подтянуть актуальный мастер

2023-10-22 15:53 UTC, mikhailchuryakov requested changes

2023-10-22 15:53 UTC, mikhailchuryakov commented on .gitignore
> +src/images/
А зачем эта строчка?

2023-10-22 18:52 UTC, antonis-white commented on .gitignore
> +src/images/
Это папка, в которую кладутся загруженные фотки (код загрузки не мой)

Во-первых Этим фоткам наверно не место в репе, а во-вторых код в репозитории падает, когда загружается фотка для объекта, фотка у которого уже есть, поэтому ci может упасть из-за фоток в этой папке

2023-10-31 06:56 UTC, mikhailchuryakov approved these changes

2023-10-31 06:56 UTC, merged