task7 - ci
mipt-backend-academy-winter-2023/team-2 pull request #24
Opened 2023-10-18 19:30 UTC by arncpp

2023-10-22 15:01 UTC, mikhailchuryakov approved these changes

2023-10-22 15:01 UTC, mikhailchuryakov commented on auth/src/test/scala/auth/Auth.scala
> +class Auth extends ZIOSpecDefault {
Для того, чтобы отделять тестовые классы от основных, обычно, добавлять суффикс Test/Suite/Spec etc (в зависимости от используемой библиотеки). В данном случае можно было бы назвать AuthSpec

2023-10-22 15:01 UTC, mikhailchuryakov commented on images/src/test/scala/images/Images.scala
> +  def assertOk(response: zio.http.Response): TestResult =
Повторяющийся код стоит выносить в какие-нибудь utils

2023-10-22 15:01 UTC, mikhailchuryakov commented on project/Libs.scala
> +  val test = "3.2.15"
Сначала не понял, что за тесты. Лучше так и назвать scalatest

2023-10-22 15:51 UTC, mikhailchuryakov requested changes

2023-10-22 15:51 UTC, mikhailchuryakov commented on images/src/test/scala/images/Images.scala
> +        assertOk(upload_image1)
Это не работает.
https://scala.monster/zio-test/#:~:text=The%20biggest%20trap%20I%20have%20fallen%20with%20ZIO%20Test.

2023-10-22 15:51 UTC, mikhailchuryakov commented on project/Libs.scala
> +  val test = "3.2.15"
Кстати, а зачем тебе эта зависимость?

2023-10-29 20:14 UTC, arncpp commented on project/Libs.scala
> +  val test = "3.2.15"
> Кстати, а зачем тебе эта зависимость?

не нужна, удалила
сначала не осознала что есть zio-test

2023-10-29 20:16 UTC, arncpp commented
Я забыла заслать ссылку на pr на edu. Вместо этого заслала форму без ответа и теперь там стоит 0 баллов.

2023-10-29 20:16 UTC, arncpp commented
> Я забыла заслать ссылку на pr на edu. Вместо этого заслала форму без ответа и теперь там стоит 0 баллов.

@mikhailchuryakov

2023-10-31 06:50 UTC, mikhailchuryakov approved these changes
Мало тестов, ребята еще другие сервисы покрыли. Эти ок

2023-10-31 06:57 UTC, closed without merging