task8/antonis-white
mipt-backend-academy-winter-2023/team-2 pull request #26
Opened 2023-10-29 18:47 UTC by antonis-white

2023-10-31 07:12 UTC, mikhailchuryakov requested changes

2023-10-31 07:12 UTC, mikhailchuryakov commented on README.md
> +<p>Прошлое задание ещё не смерджено...</p>
изменения неблокирующие, nginx и cicd не зависят друг от друга, остальные ребята сделали

2023-10-31 13:07 UTC, antonis-white commented on README.md
> +<p>Прошлое задание ещё не смерджено...</p>
Ну я у себя в задании CI чинил баги, которые были в основном коде.
Ну и в чате писали, что не обязательно до дедлайна посылать, я создал PR, чисто чтобы не было проблем с баллами на портале потом.

2023-11-15 06:01 UTC, mikhailchuryakov approved these changes

2023-11-15 06:01 UTC, closed without merging