Task3/antonis-white
mipt-backend-academy-winter-2023/team-2 pull request #8
Opened 2023-05-14 20:19 UTC by antonis-white

2023-05-16 17:50 UTC, Nikita2305 commented
++ Целевые ручки написаны, код компилируется
++ Миграции на создание и удаление базы

-- К сожалению не поднялся сервис авторизации, кажется в docker-compose не поднимается постгрес
-- Не шифруется пароль
-- При sign_up не проверяется наличие пользователя с таким же ником (что породит сайд-эффект при sign_in)

2023-06-01 11:09 UTC, mikhailchuryakov commented on docker-compose.yml
> +      - database-data:/var/lib/postgresql/data/
Невалидный докер-файл, такого вольюма не объявлено

2023-06-01 11:36 UTC, mikhailchuryakov requested changes
Невалидный докерфайл, миграции не реализованы, пароль не шифруется

2023-06-01 11:36 UTC, mikhailchuryakov commented on auth/src/main/scala/auth/flyway/FlywayAdapter.scala
> +  override def migration: UIO[Unit] = ???
not implemented :(

2023-06-01 11:36 UTC, mikhailchuryakov commented on auth/src/main/scala/auth/repo/UsersRepositoryImpl.scala
> +      //case Right(Array.empty) => ZIO.fail(new Exception("Username is taken"))
Такие комментарии в итоговый код лучше не добавлять

2023-06-01 11:36 UTC, mikhailchuryakov commented on auth/src/main/scala/auth/repo/UsersRepositoryImpl.scala
> +  private def hash(s: String): String = s
Пароль не шифруется

2023-06-01 11:36 UTC, mikhailchuryakov commented on auth/src/main/scala/auth/repo/UsersRepositoryImpl.scala
> +      ZIO.logInfo(s"Query to execute find is ${renderRead(selectUser)}")
Пароли не следует логировать даже в захешированном, а здесь хеш функция - identity

2023-06-04 15:50 UTC, mikhailchuryakov approved these changes

2023-06-04 15:50 UTC, closed without merging